# Generated by Django 2.1.7 on 2019-10-29 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reversal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateField(auto_now_add=True)),
                ('modified', models.DateField(auto_now=True)),
                ('vend_rev_time', models.CharField(max_length=300, null=True)),
                ('ref', models.CharField(max_length=300)),
                ('code', models.CharField(max_length=30)),
                ('meter', models.CharField(max_length=30)),
                ('amount', models.CharField(max_length=30)),
                ('phone_number', models.CharField(max_length=30)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateField(auto_now_add=True)),
                ('modified', models.DateField(auto_now=True)),
                ('vend_time', models.CharField(max_length=300)),
                ('reference', models.CharField(max_length=50)),
                ('code', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=150)),
                ('token', models.CharField(max_length=150)),
                ('units', models.CharField(max_length=150)),
                ('units_type', models.CharField(max_length=150)),
                ('amount', models.CharField(max_length=30)),
                ('tax', models.CharField(max_length=30)),
                ('tarrif', models.CharField(max_length=300)),
                ('description', models.CharField(max_length=30)),
                ('rct_num', models.CharField(max_length=30)),
                ('phone_number', models.CharField(max_length=14, null=True)),
                ('meter', models.CharField(max_length=50)),
                ('amount_paid', models.CharField(max_length=30)),
                ('pin', models.CharField(max_length=300)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
