# Generated by Django 2.1.7 on 2019-10-29 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vend', '0002_sms'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sms',
            old_name='linkId',
            new_name='link_id',
        ),
        migrations.RenameField(
            model_name='sms',
            old_name='networkCode',
            new_name='network_code',
        ),
    ]
