# Generated by Django 2.1.7 on 2019-10-29 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vend', '0003_auto_20191029_1217'),
    ]

    operations = [
        migrations.CreateModel(
            name='SmsSent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateField(auto_now_add=True)),
                ('modified', models.DateField(auto_now=True)),
                ('msisdn', models.CharField(max_length=20, null=True)),
                ('message', models.CharField(max_length=300)),
                ('cost', models.CharField(max_length=30)),
                ('status', models.CharField(max_length=30)),
                ('message_id', models.CharField(max_length=300)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
