# Generated by Django 2.1.7 on 2019-11-15 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vend', '0004_smssent'),
    ]

    operations = [
        migrations.AddField(
            model_name='sms',
            name='cost',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='sms',
            name='at_id',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='sms',
            name='link_id',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='sms',
            name='message',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
