# Generated by Django 2.1.7 on 2019-11-15 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vend', '0005_auto_20191115_1337'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='token',
            name='code',
        ),
    ]
