# Generated by Django 2.1.7 on 2019-11-15 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vend', '0007_auto_20191115_1706'),
    ]

    operations = [
        migrations.AddField(
            model_name='token',
            name='code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='token',
            name='address',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='token',
            name='token',
            field=models.TextField(null=True),
        ),
    ]
