# Generated by Django 2.1.7 on 2019-12-09 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vend', '0010_auto_20191209_2345'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reversal',
            name='seq',
        ),
    ]
