# Generated by Django 2.1.7 on 2020-01-14 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vend', '0011_remove_reversal_seq'),
    ]

    operations = [
        migrations.AddField(
            model_name='smssent',
            name='sent_text',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
