# Generated by Django 2.1.7 on 2020-07-01 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vend', '0012_smssent_sent_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='sms',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
