# Generated by Django 2.1.7 on 2020-07-01 02:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vend', '0013_sms_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sms',
            old_name='date_recieved',
            new_name='date_received',
        ),
    ]
