# Generated by Django 2.1.7 on 2020-08-26 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vend', '0016_remove_smssent_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('seq', models.CharField(default='00001', max_length=5)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
