# Generated by Django 2.1.7 on 2020-08-26 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vend', '0017_transaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='seq',
            field=models.CharField(max_length=5, null=True),
        ),
    ]
