# Generated by Django 2.1.7 on 2019-03-04 18:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateField(auto_now_add=True)),
                ('modified', models.DateField(auto_now=True)),
                ('pin', models.TextField(unique=True)),
                ('status', models.IntegerField(blank=True, default=0)),
                ('sid', models.CharField(blank=True, db_index=True, max_length=60, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('used_at', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(blank=True, default=False)),
                ('vendor', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CardBatch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateField(auto_now_add=True)),
                ('modified', models.DateField(auto_now=True)),
                ('denomination', models.IntegerField(blank=True, default=0)),
                ('totalcards', models.IntegerField(blank=True, default=0)),
                ('expire_at', models.DateTimeField(blank=True)),
                ('status', models.IntegerField(blank=True, default=0)),
                ('live', models.IntegerField(blank=True, default=0)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CardPreview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pin', models.CharField(max_length=20, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.IntegerField(blank=True, default=0)),
                ('printed', models.IntegerField(blank=True, default=0)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pins.CardBatch')),
            ],
        ),
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateField(auto_now_add=True)),
                ('modified', models.DateField(auto_now=True)),
                ('msisdn', models.CharField(max_length=20, unique=True)),
                ('meter', models.CharField(blank=True, max_length=20, null=True)),
                ('amount', models.IntegerField(blank=True, default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='card',
            name='batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pins.CardBatch'),
        ),
        migrations.AddField(
            model_name='card',
            name='used_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pins.Subscriber'),
        ),
    ]
