# Generated by Django 2.1.7 on 2019-03-04 18:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pins', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cardpreview',
            name='created_at',
        ),
        migrations.AddField(
            model_name='cardpreview',
            name='created',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cardpreview',
            name='modified',
            field=models.DateField(auto_now=True),
        ),
    ]
