# Generated by Django 2.1.7 on 2019-10-29 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pins', '0003_remove_card_vendor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='used_by',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
