# Generated by Django 2.1.7 on 2019-11-01 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pins', '0004_auto_20191029_1751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='pin',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='cardpreview',
            name='pin',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
