# Generated by Django 2.1.7 on 2020-08-05 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pins', '0006_auto_20200724_1010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='used_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
