# Generated by Django 2.1.7 on 2019-03-06 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='reset_password_token',
            field=models.CharField(editable=False, max_length=300, null=True),
        ),
    ]
