# Generated by Django 2.1.7 on 2020-02-03 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20190306_0751'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='login_token',
            field=models.CharField(editable=False, max_length=300, null=True),
        ),
    ]
